# Generated by Django 5.2.4 on 2025-07-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='computers_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Kompyuterlar soni'),
        ),
        migrations.AddField(
            model_name='computer',
            name='monitors_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Monitorlar soni'),
        ),
    ]
