# Generated by Django 5.2.4 on 2025-07-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0002_computer_computers_count_computer_monitors_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='keyboards_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Klaviaturalar soni'),
        ),
        migrations.AddField(
            model_name='computer',
            name='mice_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Sichqonchalar soni'),
        ),
    ]
